const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p1.jpeg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Nike Short",
      category: "Shirts",
      image: "./images/p2.jpeg",
      price: 120,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p3.jpeg",
      price: 178,
      countInStock: 7,
      brand: "Nike",
      rating: 1.1,
      numReviews: 12,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p4.jpeg",
      price: 59,
      countInStock: 6,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p5.jpeg",
      price: 310,
      countInStock: 5,
      brand: "Nike",
      rating: 4.7,
      numReviews: 11,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p6.jpeg",
      price: 240,
      countInStock: 4,
      brand: "Nike",
      rating: 4.9,
      numReviews: 8,
      description: "High Quality Product",
    },
  ],
};

export default data;
