const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./images/p1.jpeg").default,
      price: 120,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Nike Short",
      category: "Shirts",
      image: require("./images/p2.jpeg").default,
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./images/p3.jpeg").default,
      price: 178,
      brand: "Nike",
      rating: 1.1,
      numReviews: 12,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./images/p4.jpeg").default,
      price: 59,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./images/p5.jpeg").default,
      price: 310,
      brand: "Nike",
      rating: 4.7,
      numReviews: 11,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./images/p6.jpeg").default,
      price: 240,
      brand: "Nike",
      rating: 4.9,
      numReviews: 8,
      description: "High Quality Product",
    },
  ],
};

export default data;
